import Banner from "@/components/Banner/Banner";
import Best_selling_product from "@/components/Best_selling_product/Best_selling_product";
import LogoHomeSlider from "@/components/logoHomeSlider/LogoHomeSlider";
import Offer from "@/components/offer/Offer";
import Mobile_store from "@/components/Mobile_store/Mobile_store";
export const metadata = {
  title: "Pickaboo",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Banner />
      <LogoHomeSlider />
      <Offer/>
      <Best_selling_product/>
      <Mobile_store/>
    </>
  );
}
