
import type { Metadata } from "next";

import "./globals.css";

import ReduxProvider from '@/toolkit/Redux-Provider';
import Header from "@/components/Header";
import Footer from "@/components/Footer/Footer";
import { usePathname } from 'next/navigation'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body >
        <ReduxProvider>
          <Header/>
        {children}
        <Footer/>
        </ReduxProvider>
      </body>
    </html>
  );
}
