

export const menuData = [
    {
      name: { label: "SmartPhones", value: "smartphones" },
      subMenuItems: [
        { label: "Samsung", value: "samsung" },
        { label: "Infinix", value: "infinix" },
        { label: "Oppo", value: "oppo" },
        { label: "Oneplus", value: "oneplus" },
        { label: "Techno", value: "techno" },
        { label: "Nokia", value: "nokia" },
        { label: "Motorola", value: "motorola" },
        { label: "Nothing", value: "nothing" },
        { label: "Realme", value: "realme" },
        { label: "Xiaomi", value: "xiaomi" },
        { label: "Vivo", value: "vivo" },
        { label: "Iphone", value: "iphone" },
      ],
    },
    {
      name: {
        label: "Electronics & Appliances",
        value: "electronics-appliances",
      },
      subMenuItems: [
        { label: "Air Conditioner", value: "air-conditioner" },
        { label: "Television", value: "television" },
        { label: "Refrigerator & Freezer", value: "refrigerator-freezer" },
        { label: "Room Heater", value: "room-heater" },
        { label: "Air Purifier", value: "air-purifier" },
        { label: "Iron", value: "iron" },
        { label: "Geyser", value: "geyser" },
        { label: "Washing Machine", value: "washing-machine" },
        {
          label: "Home Theater & Sound System",
          value: "home-theater-sound-system",
        },
        { label: "Grinder & Blender", value: "grinder-blender" },
        { label: "Water Purifiers & Filter", value: "water-purifiers-filter" },
        { label: "Oven", value: "oven" },
        { label: "Electric Kettle", value: "electric-kettle" },
        { label: "Rice Cooker", value: "rice-cooker" },
        { label: "Air Fryer", value: "air-fryer" },
        { label: "Induction Cooker", value: "induction-cooker" },
        { label: "Gas Burner", value: "gas-burner" },
        { label: "Kitchen Hood", value: "kitchen-hood" },
        { label: "Fans", value: "fans" },
        { label: "Tools & Hardware", value: "tools-hardware" },
        { label: "IPS", value: "ips" },
  
        { label: "Exercise & Fitness", value: "exercise-fitness" },
      ],
    },
    {
      name: { label: "Mobile Accessories", value: "mobile-accessories" },
      subMenuItems: [
        { label: "Smart Watch", value: "smart-watch" },
        { label: "Smart Watch Accessories", value: "smart-watch-accessories" },
        { label: "True Wireless Airbuds", value: "true-wireless-airbuds" },
        { label: "Bluetooth Headphone", value: "bluetooth-headphone" },
        { label: "Wire Headphone", value: "wire-headphone" },
        { label: "Speaker", value: "speaker" },
        { label: "Power Band", value: "power-band" },
        { label: "Smart Band", value: "smart-band" },
        { label: "Smart Gadget", value: "smart-gadget" },
        { label: "Action Cameras", value: "action-cameras" },
        { label: "Gimbal", value: "gimbal" },
        { label: "Charger & Adapter", value: "charger-adapter" },
        { label: "Data Cable", value: "data-cable" },
        { label: "Memory Card", value: "memory-card" },
        { label: "Case & Cover", value: "case-cover" },
        { label: "Screen Protector", value: "screen-protector" },
        { label: "Selfie Sticks", value: "selfie-sticks" },
      ],
    },
    {
      name: { label: "Computer", value: "computer" },
      subMenuItems: [
        { label: "Laptop & Notebook", value: "laptop-notebook" },
        { label: "Tablet", value: "tablet" },
        { label: "Mini Pc", value: "mini-pc" },
      ],
    },
    {
      name: { label: "Computer Accessories", value: "computer-accessories" },
      subMenuItems: [
        { label: "Mouse & Keyboard", value: "mouse-keyboard" },
        { label: "IP Cameras", value: "ip-cameras" },
        { label: "Pendrives", value: "pendrives" },
        { label: "HDD & SSD", value: "hdd-ssd" },
        { label: "Monitor", value: "monitor" },
        { label: "Printer", value: "printer" },
        { label: "Headset", value: "headset" },
        { label: "Webcam", value: "webcam" },
        { label: "UPS", value: "ups" },
        { label: "Software & Antivirus", value: "software-antivirus" },
        { label: "Converter & Cable", value: "converter-cable" },
        { label: "Sound System", value: "sound-system" },
        { label: "Router & Networking", value: "router-networking" },
        { label: "Projectors", value: "projectors" },
        { label: "Gaming Gears", value: "gaming-gears" },
      ],
    },
    {
      name: { label: "LifeStyle", value: "lifestyle" },
      subMenuItems: [
        { label: "Men's Watches", value: "mens-watches" },
        { label: "Women's Watches", value: "womens-watches" },
        { label: "Shaver & Trimmer", value: "shaver-trimmer" },
        { label: "Hair Straighteners", value: "hair-straighteners" },
        { label: "Hair Dryers", value: "hair-dryers" },
        { label: "Men's Fragrances", value: "mens-fragrances" },
        { label: "Women's Fragrances", value: "womens-fragrances" },
        { label: "Scented Candles", value: "scented-candles" },
      ],
    },
  ];